### ISSUE TITLE
tfidf - input date format

### ISSUE THREAD

**Issue by trespitt** [TaddyLab/textir#2]
I have a small matrix with one column containing long strings (1 string per row). If I pass only the one data frame column to tfidf, then I get the error `rror in log(nrow(x)) : non-numeric argument to mathematical function`. If I pass the whole data frame, I get `Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric` as well as two identical warnings: `In Ops.factor(left, right) : ‘>’ not meaningful for factors`. I would be very grateful for some insight on what kind of argument this function accepts. thanks!

**Comment by mataddy** [comment]
it takes matrix arguments.  just a doc-term matrix, so you need to do the tokenization yourself.  tm package works well
